"""The outer loop: once the reviewer approves the local branch, push it, open
the pull request, wait for the full gate, and have the same reviewer session
verify the gate's logs and post the durable comment. A red gate or a late
finding goes back into the inner loop.

It stops at "ready to merge": every check and status on the head is green,
`independent-review` included. Merging code is the user's action
(`ONBOARDING.md` §7), so nothing here merges.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from .claude_runner import session_url
from .github import (
    GateRun,
    GitHub,
    HeadState,
    PullRequest,
    PullRequestDraft,
    gate_log_hits,
)
from .loop import LoopEnd, ReviewLoop, RunRecord
from .prompts import GateFiles
from .replies import DevReport, Issue, Review, Verdict
from .workspace import Workspace

_log = logging.getLogger("App.ReviewLoop")
#: A verdict line the reviewer wrote itself; the loop writes the one that counts.
_VERDICT_LINE = re.compile(r"^\s*\**\s*Verdict:.*$", re.MULTILINE)
_DISCLOSURE = "coverage disclosure"
_DISCLOSURE_REMINDER = (
    "Your comment has no Check ID Coverage Disclosure table, which the rubric "
    "requires and the `independent-review` status reads. Reply again with the "
    "same verdict and the table, under a heading containing the words "
    '"Coverage Disclosure".'
)


class PipelineEnd(StrEnum):
    READY_TO_MERGE = "ready_to_merge"
    NEEDS_HUMAN = "needs_human"


@dataclass(frozen=True)
class PipelineResult:
    end: PipelineEnd
    reason: str
    pr_url: str | None


@dataclass(frozen=True)
class GateSettings:
    base_ref: str
    check_name: str
    timeout_s: float
    settle_timeout_s: float
    poll_s: float
    max_publishes: int


@dataclass(frozen=True)
class Clock:
    monotonic: Callable[[], float]
    sleep: Callable[[float], None]


@dataclass(frozen=True)
class PublishParts:
    loop: ReviewLoop
    workspace: Workspace
    github: GitHub
    record: RunRecord


class WaitTimeoutError(RuntimeError):
    """A gate or a status had not settled on the head within its timeout."""


def durable_comment(review: Review, head: str, reviewer_session: str) -> str:
    """The reviewer's comment with the machine-read lines the loop owns: the
    reviewed head, the one verdict line, and the reviewer's session last
    (`pr-review` SKILL §7)."""
    body = _VERDICT_LINE.sub("", review.comment).rstrip()
    verdict = "PASS" if review.verdict is Verdict.APPROVE else "NEEDS_REVISION"
    return (
        f"{body}\n\nReviewed head: `{head}`\nVerdict: {verdict}\n\n---\n"
        f"_Generated by [Claude Code](https://claude.ai/code)_\n"
        f"Claude-Session: {session_url(reviewer_session)}\n"
    )


class Publisher:
    def __init__(
        self, parts: PublishParts, settings: GateSettings, clock: Clock
    ) -> None:
        self._parts = parts
        self._settings = settings
        self._clock = clock

    def run(self) -> PipelineResult:
        findings: tuple[Issue, ...] = ()
        for attempt in range(1, self._settings.max_publishes + 1):
            result = self._parts.loop.run(findings)
            if result.end is LoopEnd.NEEDS_HUMAN or result.report is None:
                return PipelineResult(PipelineEnd.NEEDS_HUMAN, result.reason, None)
            pull, head = self._publish(result.report)
            try:
                outcome = self._judge_head(pull, head, attempt)
            except WaitTimeoutError as exc:
                return PipelineResult(PipelineEnd.NEEDS_HUMAN, str(exc), pull.url)
            if isinstance(outcome, PipelineResult):
                return outcome
            findings = outcome
        return PipelineResult(
            PipelineEnd.NEEDS_HUMAN,
            f"{self._settings.max_publishes} publish attempts used",
            None,
        )

    def _judge_head(
        self, pull: PullRequest, head: str, attempt: int
    ) -> PipelineResult | tuple[Issue, ...]:
        """The pushed head's end: ready, a stop for a person, or the findings
        the developer works on next."""
        gate = self._await_gate(head)
        files = self._gate_files(pull, head, gate, attempt)
        review = self._parts.loop.review_gate(files, "")
        passing = gate.conclusion == "success" and review.verdict is Verdict.APPROVE
        if passing and _DISCLOSURE not in review.comment.lower():
            review = self._parts.loop.review_gate(files, _DISCLOSURE_REMINDER)
            if _DISCLOSURE not in review.comment.lower():
                return PipelineResult(
                    PipelineEnd.NEEDS_HUMAN,
                    "the review has no coverage disclosure",
                    pull.url,
                )
        reviewer = self._parts.loop.reviewer_session_id()
        self._parts.github.post_comment(
            pull.number, durable_comment(review, head, reviewer)
        )
        if gate.conclusion == "success" and review.verdict is Verdict.APPROVE:
            self._await_green_head(head)
            _log.info("[review-loop] %s is ready to merge at %s", pull.url, head)
            return PipelineResult(
                PipelineEnd.READY_TO_MERGE, "every check green, review PASS", pull.url
            )
        stop = self._parts.loop.stop_reason()
        if stop is not None:
            return PipelineResult(PipelineEnd.NEEDS_HUMAN, stop, pull.url)
        return self._after_gate(review, gate)

    def _publish(self, report: DevReport) -> tuple[PullRequest, str]:
        workspace = self._parts.workspace
        branch = workspace.branch()
        workspace.push(branch)
        draft = PullRequestDraft(
            branch, self._settings.base_ref, report.pr_title, report.pr_body
        )
        pull = self._parts.github.ensure_pull_request(draft)
        head = workspace.head()
        _log.info(
            "[review-loop] pushed %s at %s; pull request %s", branch, head, pull.url
        )
        return pull, head

    def _await_gate(self, head: str) -> GateRun:
        deadline = self._clock.monotonic() + self._settings.timeout_s
        while True:
            gate = self._parts.github.finished_gate(head, self._settings.check_name)
            if gate is not None:
                _log.info(
                    "[review-loop] gate on %s: %s (%s)", head, gate.conclusion, gate.url
                )
                return gate
            if self._clock.monotonic() >= deadline:
                raise WaitTimeoutError(
                    f"`{self._settings.check_name}` had not finished on {head} "
                    f"after {self._settings.timeout_s:.0f}s"
                )
            self._clock.sleep(self._settings.poll_s)

    def _await_green_head(self, head: str) -> None:
        """Waits until every check and status on `head` has passed. A failing
        status is waited on too: `independent-review` reads the comment just
        posted, and its verdict replaces the one set when the head was pushed."""
        deadline = self._clock.monotonic() + self._settings.settle_timeout_s
        state = HeadState(pending=(), failed=())
        while self._clock.monotonic() < deadline:
            state = self._parts.github.head_state(head)
            if not state.pending and not state.failed:
                return
            self._clock.sleep(self._settings.poll_s)
        raise WaitTimeoutError(
            f"checks on {head} did not all pass: failed {list(state.failed)}, "
            f"pending {list(state.pending)}"
        )

    def _gate_files(
        self, pull: PullRequest, head: str, gate: GateRun, attempt: int
    ) -> GateFiles:
        directory = self._parts.record.root / f"gate-{attempt:02d}"
        logs = self._parts.github.download_gate_logs(gate, directory)
        hits = directory / "gate-log-hits.txt"
        hits.write_text(
            gate_log_hits(logs.run_log, logs.job_log) + "\n", encoding="utf-8"
        )
        root = self._parts.workspace.root
        return GateFiles(
            pr_url=pull.url,
            head=head,
            conclusion=gate.conclusion,
            job_log=_relative(logs.job_log, root),
            run_log=_relative(logs.run_log, root) if logs.run_log is not None else None,
            grep_hits=_relative(hits, root),
        )

    def _after_gate(self, review: Review, gate: GateRun) -> tuple[Issue, ...]:
        findings = self._parts.loop.findings_after(review)
        if findings or gate.conclusion == "success":
            return findings
        return (
            Issue(
                "gate",
                gate.url,
                f"the full gate concluded `{gate.conclusion}`",
                "read the gate's job log and fix the failure at its cause",
            ),
        )


def _relative(path: Path, root: Path) -> str:
    return str(path.relative_to(root))
